config/routes.rb
NfcProject::Application.routes.draw do
  get "users/new"
  match '/signup',  to: 'users#new',            via: 'get'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/menu',    to: 'static_pages#menu',    via: 'get'
  match '/help',    to:'static_pages#help',     via: 'get'
  match '/contact', to:'static_pages#contact',  via: 'get'
  match '/about',   to:'static_pages#about',    via: 'get'
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
  end

  def help
  end

  def contact 
  end 

  def about
  end 


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   A Final Year Project
    by Group BSE 13-14
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
  
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "OrderNow!", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    home_path %></li>
          <li><%= link_to "Menu",    menu_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "SignIn", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrderNow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/shim' %>
</head>
 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About OrderNow</h1>
<p>A great application built on the blood and my shredding soul thanks to MUK </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  contact the manager at manager@gmail.com.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to OrderNow </h1>

  <h2>
    Kembabazi restuarant welcomes you. Please sign in or signup to make your order
  
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/menu.html.erb
<h1>StaticPages#menu</h1>
<p>Find me in app/views/static_pages/menu.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>